services:
  # 1. User Service
  - type: web
    name: user-service
    env: docker
    dockerfilePath: ./user-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: FRONTEND_URL
        sync: false # Ustawisz to w panelu po zdeployowaniu Netlify!
      - key: JWT_SECRET_KEY
        sync: false # Klucz wpiszesz ręcznie w panelu ze względów bezpieczeństwa
      - key: DB_HOST
        fromDatabase:
          name: servicetrack-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: servicetrack-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: servicetrack-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: servicetrack-db
          property: password

  # 2. Client Service
  - type: web
    name: client-service
    env: docker
    dockerfilePath: ./client-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: FRONTEND_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: servicetrack-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: servicetrack-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: servicetrack-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: servicetrack-db
          property: password

  # 3. Technician Service
  - type: web
    name: technician-service
    env: docker
    dockerfilePath: ./technician-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: FRONTEND_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: servicetrack-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: servicetrack-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: servicetrack-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: servicetrack-db
          property: password

  # 4. Service Order Service
  - type: web
    name: serviceorder-service
    env: docker
    dockerfilePath: ./serviceorder-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: FRONTEND_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: servicetrack-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: servicetrack-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: servicetrack-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: servicetrack-db
          property: password

databases:
  - name: servicetrack-db
    plan: free
    databaseName: servicetrack
    user: postgres